version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    restart: always
    volumes:
      - /home/$USER/.ssh:/root/.ssh
      - ./source/:/var/www/html/project
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      plt13-containers_plt13:
        ipv4_address: 172.22.0.50
  redis:
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    restart: always
    networks:
      plt13-containers_plt13:
        ipv4_address: 172.22.0.51
networks:
  plt13-containers_plt13:
    external: true